#!/bin/sh

#1-Update 
sudo apt-get update

#2-Install build-essential
sudo apt-get install build-essential

#3-Additional packages
sudo apt-get install libsdl-image1.2 libsdl-image1.2-dev guile-1.8 \
  guile-1.8-dev libsdl1.2debian libart-2.0-dev libaudiofile-dev \
  libesd0-dev libdirectfb-dev libdirectfb-extra libfreetype6-dev \
  libxext-dev x11proto-xext-dev libfreetype6 libaa1 libaa1-dev \
  libslang2-dev libasound2 libasound2-dev

#4-dowload libgraph-1.0.2.tar.gz
wget http://download.savannah.gnu.org/releases/libgraph/libgraph-1.0.2.tar.gz

#5-Extract it
tar -xvzf libgraph-1.0.2.tar.gz

#6-Execute it
cd libgraph-1.0.2
./configure
sudo make
sudo make install
sudo cp /usr/local/lib/libgraph.* /usr/lib

#7-Remove everything
cd ../
sudo rm -rf libgraph-1.0.2*

#8-Installation Done!
echo "Done!"

exit 0